version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ubuntu
